[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
phantom_paradox = "2R6Lus9psfB2dREDuC79ayfwd4peVfqG3Q42ca2iFhNV"

[programs.localnet]
phantom_paradox = "11111111111111111111111111111111"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "devnet"
wallet = "deployer_wallet.json"

[test]
startup_wait = 10000
